myproject/employees/urls.py
from django.conf import settings
from django.urls import path
from .views import home
from .views import employeeList
from .views import employeeNew
from .views import employeeEdit
from .views import employeeDelete
from .views import employeeDetail
from .views import logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home, name='home'),
    path('employees/', employeeList, name='employee_list'),
    path('employee/', employeeNew, name='employee_new'),
    path('employee_edit/<int:pk>', employeeEdit, name='employee_edit'),
    path('employee_delete/<int:pk>', employeeDelete, name='employee_delete'),
    path('employee_detail/<int:pk>', employeeDetail, name='employee_detail')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('employees.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), name='login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'HR Management'
admin.site.site_title = 'Administration'
admin.site.index_title = "Version 1.0"

myproject/employees/models.py
from django.db import models


# Create Category Model
class Category(models.Model):
	cat_name = models.CharField(max_length=50)
	cat_salary = models.FloatField(blank=True)

	def __str__(self):
		return self.cat_name


class Department(models.Model):
	dep_acronym = models.CharField(max_length=10)
	dep_name = models.CharField(max_length=50)
	dep_address = models.CharField(max_length=50, blank=True)
	dep_email = models.EmailField(max_length=50, blank=True)
	dep_phone = models.IntegerField(blank=True)

	def __str__(self):
		return self.dep_acronym + ' - ' + self.dep_name


# Create Employee Model
class Employee(models.Model):
	cod = models.IntegerField()
	name = models.CharField(max_length=40)
	last_name = models.CharField(max_length=20)
	civil_status = models.CharField(max_length=20, blank=True)
	photo = models.ImageField(upload_to='photos', blank=True)
	degree = models.CharField(max_length=30, blank=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	department = models.ForeignKey(Department, on_delete=models.CASCADE)
	bio = models.TextField(max_length=200, blank=True)
	birth = models.DateTimeField(blank=True)
	address = models.CharField(max_length=100)
	email = models.EmailField(blank=True)
	city = models.CharField(max_length=20)
	created_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name + ' ' + self.last_name


# Create Document Model
class Document(models.Model):
	doc_number = models.IntegerField()
	doc_name = models.CharField(max_length=20)
	doc_date = models.DateField(auto_now_add=True)
	doc_file = models.FileField(upload_to='files', blank=True)
	employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

	def __str__(self):
		return self.employee.last_name + ' - ' + self.doc_name

myproject/employees/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .models import Employee
from .models import Department
from .models import Category
from .models import Document
from .form import EmployeeForm


# Create home view
def home(request):
    return render(request, 'home.html')


@login_required
def employeeList(request):
    employees = Employee.objects.all()
    return render(request, 'employeelist.html', {'employees':employees})


@login_required
def employeeNew(request):
    form = EmployeeForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        return redirect('employee_list')
    return render(request, 'employee.html', {'form':form})


@login_required
def employeeEdit(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    form = EmployeeForm(request.POST or None, request.FILES or None, instance=employee)

    if form.is_valid():
        form.save()
        return redirect('employee_list')
    return render(request, 'employee.html', {'form':form})


@login_required
def employeeDelete(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    if request.method == 'POST':
        employee.delete()
        return redirect('employee_list')
    return render(request, 'delete.html', {'employee':employee})


@login_required
def employeeDetail(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    documents = Document.objects.filter(employee_id=employee.id)
    return render(request, 'detail.html', {'employee':employee, 'documents':documents})

myproject/employees/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HRM</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"> HRM </div>
      <div class="list-group list-group-flush">
        <a href="/" class="list-group-item list-group-item-action bg-light">Home</a>
        <a href="{% url 'employee_list' %}" class="list-group-item list-group-item-action bg-light">Employees</a>
        <a href="{% url 'employee_new' %}" class="list-group-item list-group-item-action bg-light">New Employee</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="">Hello, <b>{{user.last_name}}</b></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
          {% block content %}

          {% endblock content %}
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>

  <footer>
      {% block footer %}

      {% endblock footer %}
  </footer>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </script>

</body>

</html>

myproject/employees/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

        <h3>Delete Employee</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Are you confirm want to delete <b>{{employee.name}} {{employee.last_name}}?</p>
            <input type="submit" value="yes" class="btn btn-primary btn-xs pull-right"/>
            <a href="/employees" class="btn btn-info btn-xst">No</a>
        </form>
</div>
{% endblock content %}

myproject/employees/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h3>Employees Details</h3>
    <img src="/media/{{employee.photo}}" class="img-fluid" alt="Responsive image" width="100" height="50">
    <form>
        <label>Employee Code</label>
        <input class="form-control" type="text" placeholder="{{employee.cod}}" readonly>
        <label>Name</label>
        <input class="form-control" type="text" placeholder="{{employee.name}} {{employee.last_name}}" readonly>
        <label>Department</label>
        <input class="form-control" type="text" placeholder="{{employee.department.dep_name}}" readonly>
        <label>Degree</label>
        <input class="form-control" type="text" placeholder="{{employee.degree}}" readonly>
        <label>Degree</label>
        <input class="form-control" type="text" placeholder="{{employee.degree}}" readonly>
         <label>Email</label>
        <input class="form-control" type="text" placeholder="{{employee.email}}" readonly>
        <label>Documents</label>
    </form>
    {% for document in documents %}
        <a href="/media/{{document.doc_file}}"
           class="btn btn-primary btn-xs pull-right" download>{{document.doc_name}}</a>
    {% endfor %}

</div>
{% endblock content %}

myproject/employees/templates/employee.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h3>New Employee</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                {{ form }}
            </tr>
        </table>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
<style>
    #id_name, #id_cod, #id_last_name, #id_civil_status, #id_photo, #id_degree, #id_category, #id_department,
    #id_birth, #id_bio, #id_address, #id_city, #id_email{
        width: 400px;
    }
</style>
{% endblock %}

myproject/employees/templates/employeelist.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
    <div class="row col-md-12 col-md-offset-2 custyle">
    <table class="table table-striped custab">
    <thead>
        <tr>
            <th>Card</th>
            <th>Name</th>
            <th>Last Name</th>
            <th class="text-center"></th>
        </tr>
    </thead>
        {% for employee in employees %}
            <tr>
                <td>{{employee.cod}}</td>
                <td>{{employee.name}}</td>
                <td>{{employee.last_name}}</td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="{% url 'employee_edit' employee.id %}">
                    <span class="glyphicon glyphicon-edit"></span> Edit</a>
                    <a href="{% url 'employee_delete' employee.id %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a>
                    <a href="{% url 'employee_detail' employee.id %}" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-edit"></span> Details</a>
                </td>
            </tr>
        {% endfor %}
    </table>
        <a href="/employee" class="btn btn-primary btn-xs pull-right"><b>+</b> Add new Employee</a>
    </div>
{% endblock %}

myproject/employees/templates/home.html
{% extends 'base.html' %}


{% block content %}
  <h2>Welcome to HRM</h2>
  <span> Human Resources Management</span>
{% endblock %}